# Generated by Django 3.0.2 on 2020-06-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
