# Generated by Django 3.0.2 on 2020-07-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200626_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ed3ab4', max_length=20, unique=True),
        ),
    ]
