# Generated by Django 3.0.2 on 2020-05-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20200523_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='e5ee8b', max_length=20, unique=True),
        ),
    ]
