# Generated by Django 3.0.2 on 2020-05-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20200523_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='c1514d', max_length=20, unique=True),
        ),
    ]
