# Generated by Django 3.0.2 on 2020-05-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20200523_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='8f7ca8', max_length=20, unique=True),
        ),
    ]
