# Generated by Django 3.0.2 on 2020-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_auto_20200529_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1b9a65', max_length=20, unique=True),
        ),
    ]
