# Generated by Django 3.0.2 on 2020-05-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_auto_20200531_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='appointment_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_schedules', to='carts.AppointmentSchedule'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='6a46a7', max_length=20, unique=True),
        ),
    ]
