# Generated by Django 3.0.2 on 2020-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_auto_20200531_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='97a8ea', max_length=20, unique=True),
        ),
    ]
