# Generated by Django 3.0.2 on 2020-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_auto_20200602_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='9b461d', max_length=20, unique=True),
        ),
    ]
