# Generated by Django 3.0.2 on 2020-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_auto_20200602_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='41ba1e', max_length=20, unique=True),
        ),
    ]
