# Generated by Django 3.0.2 on 2020-06-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0021_auto_20200604_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='0ea70f', max_length=20, unique=True),
        ),
    ]
