# Generated by Django 3.0.2 on 2020-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_auto_20200604_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='6e57e7', max_length=20, unique=True),
        ),
    ]
