# Generated by Django 3.0.2 on 2020-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0024_auto_20200605_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='cd3b99', max_length=20, unique=True),
        ),
    ]
