# Generated by Django 3.0.2 on 2020-06-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0025_auto_20200605_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='af04da', max_length=20, unique=True),
        ),
    ]
