# Generated by Django 3.0.2 on 2020-06-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0026_auto_20200607_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='84ceff', max_length=20, unique=True),
        ),
    ]
