# Generated by Django 3.0.2 on 2020-06-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0029_auto_20200613_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='c47aa6', max_length=20, unique=True),
        ),
    ]
