# Generated by Django 3.0.2 on 2020-06-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0031_auto_20200616_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='eacf95', max_length=20, unique=True),
        ),
    ]
