# Generated by Django 3.0.2 on 2020-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0032_auto_20200617_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='53dd2e', max_length=20, unique=True),
        ),
    ]
