# Generated by Django 3.0.2 on 2020-05-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('services', '0002_service_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='service',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Area'),
        ),
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.City'),
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Country'),
        ),
        migrations.AddField(
            model_name='service',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Division'),
        ),
    ]
