# Generated by Django 3.0.2 on 2020-05-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200518_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='services.Service'),
        ),
    ]
