# Generated by Django 3.0.2 on 2020-06-05 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_auto_20200524_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceapproves', to=settings.AUTH_USER_MODEL),
        ),
    ]
