# Generated by Django 3.0.2 on 2020-05-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200518_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
