# Generated by Django 3.0.2 on 2020-05-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_auto_20200526_2147'),
        ('appointments', '0003_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_schedule',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='mobile',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='carts.CartItem'),
        ),
        migrations.DeleteModel(
            name='AppointmentSchedule',
        ),
    ]
