# Generated by Django 3.0.2 on 2020-06-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20200526_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
