# Generated by Django 3.0.2 on 2020-06-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('degrees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degreeapproves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='degree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
