# Generated by Django 3.0.2 on 2020-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0004_auto_20200605_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
