# Generated by Django 3.0.2 on 2020-05-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmdc_number', models.CharField(blank=True, max_length=30, null=True)),
                ('current_position', models.CharField(blank=True, max_length=50, null=True)),
                ('current_working_department', models.CharField(blank=True, max_length=200, null=True)),
                ('current_working_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality_details', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
