# Generated by Django 3.0.2 on 2020-06-05 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0003_auto_20200518_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stuffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
