# Generated by Django 3.0.2 on 2020-06-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20200605_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
