# Generated by Django 3.0.2 on 2020-06-16 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0007_auto_20200616_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speciality_approves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speciality',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
